# Generated by Django 5.2.1 on 2025-05-21 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('position', models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child'), ('GRANDPARENT', 'Grandparent'), ('PET', 'Pet')], default='PARENT', max_length=100, verbose_name='позиция')),
                ('age', models.IntegerField(default=25, verbose_name='возраст')),
                ('is_owner', models.BooleanField(default=False, verbose_name='является ли владельцем')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Family', max_length=200, verbose_name='название')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='сумма общего кошелька')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='владелец_семьи', to='user.customuser', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'семья',
                'verbose_name_plural': 'семьи',
            },
        ),
        migrations.CreateModel(
            name='FamilyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='семья_связь', to='user.family', verbose_name='семья')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='член_семьи_связь', to='user.customuser', verbose_name='член семьи')),
            ],
            options={
                'verbose_name': 'член семьи',
                'verbose_name_plural': 'члены семьи',
            },
        ),
    ]
