# Generated by Django 5.2.1 on 2025-05-22 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='статус')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('invented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='приглашающий_кто', to=settings.AUTH_USER_MODEL, verbose_name='приглашающий')),
            ],
            options={
                'verbose_name': 'приглашение',
                'verbose_name_plural': 'приглашения',
            },
        ),
    ]
