# Generated by Django 5.2.1 on 2025-05-21 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='сумма')),
                ('type', models.CharField(choices=[('EXPENSES', 'Expenses'), ('INCOME', 'Income')], default='EXPENSES', max_length=20, verbose_name='тип')),
                ('comment', models.CharField(max_length=250, null=True, verbose_name='комментарий')),
                ('datetime_created', models.DateField(default=django.utils.timezone.now, verbose_name='дата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='категория_транзакции', to='transaction.category', verbose_name='категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='пользователь_транзакции', to='user.customuser', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'транзакция',
                'verbose_name_plural': 'транзакции',
            },
        ),
    ]
